### ISSUE TITLE
pytest, linting, code formatting, pipenv

### ISSUE THREAD

**Issue by ShivanS93** [mrdbourke/nutrify#1]
# Related PR: #4 

I understand that we want simplicity, but it is also a good idea to slowly include coding best practices...

- incorporate `pytest` for automated testing
- also have pre-commit hooks for linting, (`mypy`, `flake8`) and code formating `black`.
- switch to `pipenv` for package management instead of a `requirements.txt`, we can manage production packages (e.g. `streamlit`) and the above dev pages separately.

## Some resources:
- https://docs.pytest.org/en/6.2.x/
- https://shivansivakumaran.com/coding/my-tubestats-app/#Hurdle_6_how_to_test_code
- https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/
- https://pipenv.pypa.io/en/latest/

**Comment by ShivanS93** [comment]
# Precommit hooks to include 

Install `pre-commit` onto you system using `pip`:

```shell
pip install pre-commit
```

Include the following code in the `.pre-commit-config.yaml` file, in the root directory of the project.

```yaml
# .pre-commit-config.yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/ambv/black
    rev: 21.7b0
    hooks:
    -   id: black
        args: [--line-length=79]
        language_version: python3.8

-   repo: https://github.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    -   id: mypy
```
Install these to git hook. 
```
pre-commit install 
```
Everything a git commit is run these checks will run. This ensures the code is clean.

```shell
git add .
git commit -m 'message'
# Pre commit hooks will run
```
These pre-commit hooks include:
- `black` - [a python code formatter](https://pypi.org/project/black/)
- `mypy` - [a static type checker](http://mypy-lang.org/) 
- `flake8` - [a style guide checker](https://flake8.pycqa.org/en/latest/)

If this becomes a pain, you can always by pass the pre-commit hooks with the `-n` tag.
```shell
git commit -n -m 'bypassing hooks lulz'

Enjoy!
