### ISSUE TITLE
Trying to set up locally... and looking at dependancies

### ISSUE THREAD

**Issue by ShivanS93** [mrdbourke/nutrify#7]
This is for the no urgent todos...

Trying to set this up locally but having trouble setting up secrets.toml. 

Errors I'm getting are missing fields for token_uri and client_email.

I am able to reduce the number of dependencies too. (Dan, you may have used your local environment, which contains ALL you installed packages instead of creating a virtualenv.

```toml
# my new Pipfile
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
streamlit = "*"
google-api-python-client = "*"
google-auth-httplib2 = "*"
google-auth-oauthlib = "*"
rich = "*"
google-cloud-storage = "*"

[dev-packages]
pytest = "*"

[requires]
python_version = "3.8"
```
